# Generated by Django 3.0.8 on 2020-07-10 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_auto_20200710_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='date_addes',
            new_name='date_added',
        ),
    ]
